### ISSUE TITLE
Emoji hinzufügen zur Anwendung

### ISSUE THREAD

**Issue by skywalkeretw** [skywalkeretw/DBE-Humor-Prototype#8]
Passe die HTML Seite so an das die Prozentzahl ob es ein Witz ist oder nicht als Emoji ausgegeben wird

hier ist die doku um das HTML template anzupassen https://flask.palletsprojects.com/en/2.2.x/tutorial/templates/

die Einfachtste option wäre es die url zu einem bild an das template zu übergeben davon abhängig was auf dem emoji drauf soll

*Der code ist nur ein Vorschlag wie man es machen kann, feel free to do it how you like 👍 *

```python
if is_joke <= 10
 url="trauriges emoji"
elif...

render_template('index.html', ... url=url)
```

```html
<img src="{{ url }}"
```

**Comment by KekUpdate** [comment]
done
